package com.openrent.cambridge.data

import android.content.Context
import com.openrent.cambridge.model.Journey
import com.openrent.cambridge.model.Leg
import com.openrent.cambridge.model.Stop
import com.openrent.cambridge.model.TransitData
import com.openrent.cambridge.model.parseHhMm
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject

/**
 * Loads the bundled timetable. The asset is generated by
 * tools/generate_transit_asset.py from real published GB timetable data; the app
 * itself never queries a transit API, so search works offline and instantly.
 */
class TransitRepository(private val context: Context) {

    companion object {
        const val ASSET = "transit_waterbeach.json"


        /**
         * The generator discovers boarding points per origin, so the same stop can
         * appear twice with slightly different coordinates (separate platforms or
         * entrances). Merge those into one stop with the union of their journeys,
         * so a stop is not artificially split across two thin timetables.
         */
        internal fun mergeDuplicateStops(stops: List<Stop>): List<Stop> =
            stops.groupBy { it.name to it.mode }
                .map { (_, group) ->
                    if (group.size == 1) return@map group.first()
                    val journeys = group
                        .flatMap { it.journeys }
                        .distinctBy { it.dep to it.arrWaterbeach }
                        .sortedBy { it.dep }
                    group.maxByOrNull { it.journeys.size }!!.copy(journeys = journeys)
                }

        /** Exposed so unit tests can validate the shipped asset without Android. */
        fun parse(json: String): TransitData {
            val root = JSONObject(json)
            val dest = root.getJSONObject("destination")
            val wb = root.getJSONObject("waterbeachStation")
            val lastMile = root.getJSONObject("lastMile")
            val stopsArr = root.getJSONArray("stops")

            val stops = (0 until stopsArr.length()).map { i ->
                val s = stopsArr.getJSONObject(i)
                val area = s.getJSONObject("searchArea")
                val jArr = s.getJSONArray("journeys")
                val journeys = (0 until jArr.length()).mapNotNull { k ->
                    val j = jArr.getJSONObject(k)
                    val dep = parseHhMm(j.getString("dep")) ?: return@mapNotNull null
                    val arr = parseHhMm(j.getString("arrWaterbeach")) ?: return@mapNotNull null
                    val lArr = j.getJSONArray("legs")
                    val legs = (0 until lArr.length()).mapNotNull { m ->
                        val l = lArr.getJSONObject(m)
                        Leg(
                            mode = l.optString("mode"),
                            route = l.optString("route"),
                            from = l.optString("from"),
                            to = l.optString("to"),
                            dep = parseHhMm(l.optString("dep")) ?: return@mapNotNull null,
                            arr = parseHhMm(l.optString("arr")) ?: return@mapNotNull null
                        )
                    }
                    Journey(dep = dep, arrWaterbeach = arr, legs = legs)
                }.sortedBy { it.dep }

                Stop(
                    id = s.getString("id"),
                    name = s.getString("name"),
                    areaName = s.optString("areaName", s.getString("name")),
                    mode = s.getString("mode"),
                    lat = s.getDouble("lat"),
                    lon = s.getDouble("lon"),
                    searchTerm = area.getString("term"),
                    searchSlug = area.getString("slug"),
                    journeys = journeys
                )
            }.let(::mergeDuplicateStops)

            return TransitData(
                validFrom = root.getString("validFrom"),
                serviceDate = root.optString("serviceDate"),
                source = root.optString("source"),
                crpLat = dest.getDouble("lat"),
                crpLon = dest.getDouble("lon"),
                waterbeachLat = wb.getDouble("lat"),
                waterbeachLon = wb.getDouble("lon"),
                cycleLastMileMin = lastMile.getInt("cycleMin"),
                shuttleLastMileMin = lastMile.getInt("shuttleMin"),
                stops = stops
            )
        }
    }

    @Volatile private var cached: TransitData? = null

    suspend fun load(): TransitData = cached ?: withContext(Dispatchers.IO) {
        val json = context.assets.open(ASSET).bufferedReader().use { it.readText() }
        parse(json).also { cached = it }
    }
}
